### ISSUE TITLE
Consider cross-session cache for RUIAN files

### ISSUE THREAD

**Issue by petrbouchal** [JanCaha/CzechData#7]
I use `load_ruian_*()` a lot, esp. for whole country and Prague. These are large files that don't change very often so I would  appreciate the ability to store the source files in a per-project or system-wide cache.

One way might be to provide an analogue to the `save_data50()` function and provide a way to feed the file to the `load_ruian_*()` function.

FWIW I had to handle a similar problem in `statnipokladna` and `czso` - see e.g. https://github.com/petrbouchal/statnipokladna/blob/master/NEWS.md#improvements.

An alternative might be using `{memoise}` which I spotted in [`{weathercan}`](https://github.com/ropensci/weathercan/blob/master/NEWS.md)

**Comment by JanCaha** [comment]
Should be working now :)

Implemented using `{memoise}` and set to last for 7 days. Once I have more free time I will add a package option to set the cache time more specifically.

**Comment by petrbouchal** [comment]
Wonderful, thank you! I ran into an error and attempted to fix it in https://github.com/JanCaha/CzechData/pull/8 -  see if that is OK for you.

I still get re-downloads after session restart (I think that may be caused by the use of `tempdir()`?) but this is already an improvement!

Leaving to you to close and move next steprs into new issues as you see fit.

**Comment by JanCaha** [comment]
The error is actually somewhere else. Much more simpler and stupider 👎 

I prepared the functions to set and get cache length but actually forgot to use them in the necessary place (see 955b4eb005b8144a9a4daff6b534078e27484463) ;-)

The PR would solve the problem but not exactly correctly, the set and get functions would have no effect then.

**Comment by petrbouchal** [comment]
Ah well, hasty work on my part. Thanks for catching it.
